.github/workflows/upstream-sync.yml

This pull request includes updates to the `.github/workflows/upstream-sync.yml` file to modify the workflow triggers and improve the merge process for pull requests.
Changes to workflow triggers:
* Removed the `pull_request` trigger for the `dev` branch.
Enhancements to merge process:
* Updated the merge command to use the `--admin` flag for administrative merging of pull requests.

ci: update upstream sync

---

.github/workflows/upstream-sync.yml

This pull request includes several updates to the `.github/workflows/upstream-sync.yml` file to improve the synchronization process with the upstream repository. The main changes include enhancing the fetch strategy, updating branch synchronization, and refining the tagging process.
Improvements to fetch strategy and branch synchronization:
* [`.github/workflows/upstream-sync.yml`](diffhunk://#diff-f21bf02175f33f2522bf5ac7944d2999c7f4ea8b8542afe361a9800eda3580e9L19-R19): Added a comment to clarify the fetch-depth setting to fetch all history for all branches and tags.
* [`.github/workflows/upstream-sync.yml`](diffhunk://#diff-f21bf02175f33f2522bf5ac7944d2999c7f4ea8b8542afe361a9800eda3580e9L40-R53): Changed the fetch command to fetch the complete history from upstream and ensured the …

ci: update tag upstream sync

---

.github/workflows/upstream-sync.yml

This pull request includes changes to the `.github/workflows/upstream-sync.yml` file to update the tagging process and ensure it works correctly with the `dev` branch instead of the `master` branch.
Updates to the tagging process:
* Modified the script to fetch and checkout the `dev` branch before creating a tag.
* Updated the tag existence check to look for tags on the `dev` branch instead of the `master` branch.
* Changed the tag creation process to create the tag on the `dev` branch HEAD after the merge.
* Updated the success message to indicate the total commits from the `master` branch.

ci: tag commit after sync on dev branch

---

ci/README.md
ci/run.sh
docs/build.md
examples/run/run.cpp
ggml/src/ggml-cpu/CMakeLists.txt
ggml/src/ggml-cpu/kleidiai/kernels.cpp
ggml/src/ggml-cpu/kleidiai/kernels.h
ggml/src/ggml-cpu/kleidiai/kleidiai.cpp
ggml/src/ggml-sycl/ggml-sycl.cpp
src/llama-context.cpp

Updates dev branch with latest release (b4958) from ggml-org/llama.cpp

Sync master with upstream release b4958

---

.github/workflows/upstream-sync.yml

This pull request includes a change to the `.github/workflows/upstream-sync.yml` file to streamline the tagging process

chore: update ci create tag on dev branch

---

common/sampling.cpp
examples/rpc/CMakeLists.txt
examples/rpc/README.md
examples/rpc/rpc-server.cpp
examples/server/server.cpp
ggml/include/ggml-rpc.h
ggml/include/ggml.h
ggml/src/ggml-cpu/ggml-cpu.c
ggml/src/ggml-cpu/llamafile/sgemm.cpp
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-metal/ggml-metal-impl.h
ggml/src/ggml-metal/ggml-metal.m
ggml/src/ggml-metal/ggml-metal.metal
ggml/src/ggml-rpc/ggml-rpc.cpp
ggml/src/ggml-vulkan/CMakeLists.txt
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/CMakeLists.txt
ggml/src/ggml.c
include/llama.h
src/llama-context.cpp
src/llama-model.cpp
src/llama-sampling.cpp
tests/test-backend-ops.cpp

Updates dev branch with latest release (b4988) from ggml-org/llama.cpp

Sync master with upstream release b4988

---

ggml/src/ggml-cuda/cpy.cu
ggml/src/ggml-cuda/fattn-common.cuh
ggml/src/ggml-cuda/fattn-tile-f32.cu
ggml/src/ggml-cuda/fattn-vec-f32.cuh
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm2.comp

Updates dev branch with latest release (b5061) from ggml-org/llama.cpp

Sync master with upstream release b5061

---

common/common.cpp
examples/llava/clip.cpp
examples/rpc/rpc-server.cpp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm2.comp

Updates dev branch with latest release (b5124) from ggml-org/llama.cpp

Sync master with upstream release b5124

---

examples/quantize/quantize.cpp
ggml/src/ggml-cuda/ggml-cuda.cu
include/llama.h
src/llama-quant.cpp

Updates dev branch with latest release (b5126) from ggml-org/llama.cpp

Sync master with upstream release b5126

---

ggml/src/ggml-cann/aclnn_ops.cpp
ggml/src/ggml-cann/ggml-cann.cpp
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm2.comp
tests/test-backend-ops.cpp

Updates dev branch with latest release (b5145) from ggml-org/llama.cpp

Sync master with upstream release b5145

---

ggml/src/ggml-cann/aclnn_ops.cpp
ggml/src/ggml-cann/aclnn_ops.h
ggml/src/ggml-cann/common.h
ggml/src/ggml-cann/ggml-cann.cpp
ggml/src/ggml-cuda/cpy.cu
ggml/src/ggml-cuda/cpy.cuh
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-metal/ggml-metal.m
ggml/src/ggml-metal/ggml-metal.metal
ggml/src/ggml-vulkan/ggml-vulkan.cpp
src/llama-context.cpp
src/llama-graph.cpp
src/llama-model.cpp
src/llama-vocab.cpp
tests/test-backend-ops.cpp

Updates dev branch with latest release (b5149) from ggml-org/llama.cpp

Sync master with upstream release b5149

---

.github/workflows/build.yml
examples/llava/clip.cpp
gguf-py/pyproject.toml

Updates dev branch with latest release (b5158) from ggml-org/llama.cpp

Sync master with upstream release b5158

---

convert_hf_to_gguf.py
convert_lora_to_gguf.py
examples/llava/clip-impl.h
examples/llava/clip.h
ggml/src/ggml-metal/ggml-metal.m
ggml/src/ggml-metal/ggml-metal.metal
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/rms_norm.comp
gguf-py/gguf/constants.py
gguf-py/gguf/tensor_mapping.py

Updates dev branch with latest release (b5162) from ggml-org/llama.cpp

Sync master with upstream release b5162

---

examples/llava/clip.cpp
ggml/include/ggml-rpc.h
ggml/src/ggml-rpc/ggml-rpc.cpp
ggml/src/ggml-sycl/common.hpp
ggml/src/ggml-sycl/ggml-sycl.cpp
src/llama-context.cpp
src/llama-context.h
src/llama-graph.cpp
tests/test-backend-ops.cpp

Updates dev branch with latest release (b5191) from ggml-org/llama.cpp

Sync master with upstream release b5191

---

common/arg.cpp
common/arg.h
common/json-schema-to-grammar.cpp
examples/json_schema_to_grammar.py
examples/llava/clip-impl.h
examples/llava/clip.cpp
examples/llava/clip.h
examples/server/public_legacy/json-schema-to-grammar.mjs
ggml/include/ggml-cpu.h
ggml/src/ggml-cpu/ggml-cpu.c
ggml/src/ggml-cpu/ops.cpp
ggml/src/ggml.c
tests/test-arg-parser.cpp
tests/test-json-schema-to-grammar.cpp

Updates dev branch with latest release (b5195) from ggml-org/llama.cpp

Sync master with upstream release b5195

---

convert_hf_to_gguf.py
examples/llama-bench/llama-bench.cpp
examples/llava/clip-impl.h
examples/llava/clip.cpp
examples/llava/qwen2_vl_surgery.py
examples/llava/qwen2vl-cli.cpp
examples/llava/tests.sh
ggml/src/ggml-cuda/cpy.cu
src/llama-chat.cpp

Updates dev branch with latest release (b5200) from ggml-org/llama.cpp

Sync master with upstream release b5200

---

ggml/src/ggml-sycl/CMakeLists.txt

Updates dev branch with latest release (b5351) from ggml-org/llama.cpp

Sync master with upstream release b5351

---

common/minja/chat-template.hpp
common/minja/minja.hpp

Updates dev branch with latest release (b5401) from ggml-org/llama.cpp

Sync master with upstream release b5401

---

.github/workflows/release.yml
.github/workflows/winget.yml
ggml/src/ggml-cpu/ggml-cpu.c
ggml/src/ggml-cuda/fattn-vec-f16.cuh
ggml/src/ggml-cuda/fattn-vec-f32.cuh
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-cuda/unary.cu
ggml/src/ggml-cuda/unary.cuh
src/llama-graph.cpp
src/llama-vocab.cpp

Updates dev branch with latest release (b5477) from ggml-org/llama.cpp

Sync master with upstream release b5477

---

common/arg.cpp
common/chat.cpp
common/chat.h
common/common.h
ggml/src/ggml-cpu/CMakeLists.txt
ggml/src/ggml-metal/ggml-metal.m
ggml/src/ggml-metal/ggml-metal.metal
ggml/src/ggml-sycl/ggml-sycl.cpp
ggml/src/ggml-sycl/mmvq.cpp
ggml/src/ggml-sycl/vecdotq.hpp
src/llama-model.cpp
tests/test-chat.cpp
tools/mtmd/mtmd-cli.cpp
tools/mtmd/mtmd-helper.cpp
tools/server/server.cpp
tools/server/tests/unit/test_tool_call.py
tools/server/tests/utils.py

Updates dev branch with latest release (b5579) from ggml-org/llama.cpp

Sync master with upstream release b5579

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/server.yml
README.md
docs/build.md
docs/install.md
ggml/src/ggml-cpu/ops.cpp
ggml/src/ggml-cuda/fattn-mma-f16.cuh
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/conv_transpose_1d.comp
ggml/src/ggml-vulkan/vulkan-shaders/vulkan-shaders-gen.cpp
src/llama-context.cpp
src/llama-context.h
src/llama-graph.cpp
src/llama-kv-cache-recurrent.cpp
src/llama-kv-cache-recurrent.h
src/llama-kv-cache-unified-iswa.cpp
src/llama-kv-cache-unified-iswa.h
src/llama-kv-cache-unified.cpp
src/llama-kv-cache-unified.h
src/llama-kv-cache.h
src/llama-memory.cpp
src/llama-memory.h
tests/test-backend-ops.cpp

Updates dev branch with latest release (b5590) from ggml-org/llama.cpp

Sync master with upstream release b5590

---

.github/workflows/upstream-sync.yml

This pull request introduces a new GitHub Actions workflow to automate the synchronization of the repository with the upstream `ggml-org/llama.cpp` repository. The workflow ensures that the `master` branch is updated with the latest upstream release, creates a pull request to merge the changes into the `dev` branch, and handles tagging and CI checks. Below are the key changes:
* **Workflow Definition**: Added a new workflow file `.github/workflows/upstream-sync.yml` to automate syncing with the upstream repository. The workflow is triggered daily at midnight UTC or manually via `workflow_dispatch`.
* **Syncing Process**: 
- Fetches the latest release from the upstream repository and updates the `master` branch accordingly.
- Pushes the updated `master` branch to the repository.
* **Pull …

ci: add upstream sync workflow

---

common/arg.cpp
common/common.h
ggml/src/ggml-cuda/cpy-utils.cuh
ggml/src/ggml-cuda/cpy.cu
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-cuda/set-rows.cu
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/rms_norm.comp
src/llama-model.cpp
tools/imatrix/README.md
tools/imatrix/imatrix.cpp
tools/mtmd/clip.cpp

Updates dev branch with latest release (b5963) from ggml-org/llama.cpp

Sync master with upstream release b5963

---

.github/workflows/close-issue.yml
ggml/src/ggml-cann/aclnn_ops.cpp
ggml/src/ggml-cann/aclnn_ops.h
ggml/src/ggml-cann/ggml-cann.cpp
ggml/src/ggml-cpu/arch/loongarch/quants.c
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/fattn-common.cuh
ggml/src/ggml-cuda/fattn-mma-f16.cuh
ggml/src/ggml-cuda/fattn-tile-f16.cu
ggml/src/ggml-cuda/fattn-tile-f32.cu
ggml/src/ggml-cuda/fattn-vec-f16.cuh
ggml/src/ggml-cuda/fattn-vec-f32.cuh
ggml/src/ggml-cuda/fattn-wmma-f16.cu
ggml/src/ggml-cuda/fattn.cu
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-cuda/norm.cu
ggml/src/ggml-cuda/norm.cuh
gguf-py/gguf/metadata.py
src/llama-memory-recurrent.cpp
tests/test-backend-ops.cpp

Updates dev branch with latest release (b5973) from ggml-org/llama.cpp

Sync master with upstream release b5973

---

docs/build-s390x.md
docs/development/HOWTO-add-model.md
ggml/CMakeLists.txt
ggml/src/ggml-backend.cpp
ggml/src/ggml-cpu/CMakeLists.txt
ggml/src/ggml-metal/ggml-metal-impl.h
ggml/src/ggml-metal/ggml-metal.m
ggml/src/ggml-metal/ggml-metal.metal
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-opencl/kernels/rms_norm.cl
ggml/src/ggml-rpc/ggml-rpc.cpp
ggml/src/ggml.c
src/llama-context.cpp
src/llama-context.h
tools/export-lora/export-lora.cpp
tools/mtmd/clip.cpp

Updates dev branch with latest release (b5994) from ggml-org/llama.cpp

Sync master with upstream release b5994

---

.github/workflows/pre-tokenizer-hashes.yml
common/chat.cpp
convert_hf_to_gguf.py
convert_hf_to_gguf_update.py
ggml/src/ggml-cuda/fattn.cu
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-cuda/im2col.cu
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-sycl/ggml-sycl.cpp
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/mul_mat_vec_nc.comp
gguf-py/gguf/tensor_mapping.py
requirements/requirements-convert_hf_to_gguf_update.txt
scripts/compare-llama-bench.py
src/llama-context.cpp
src/llama-context.h
src/llama-kv-cache-unified.cpp
src/llama-kv-cache-unified.h
src/llama-model.cpp
tests/test-backend-ops.cpp
tests/test-chat.cpp
tools/llama-bench/llama-bench.cpp

Updates dev branch with latest release (b6075) from ggml-org/llama.cpp

Sync master with upstream release b6075

---

common/arg.cpp
common/common.h
convert_hf_to_gguf.py
convert_hf_to_gguf_update.py
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/conv2d_mm.comp
ggml/src/ggml-vulkan/vulkan-shaders/vulkan-shaders-gen.cpp
gguf-py/gguf/vocab.py
src/llama-memory-hybrid.cpp
src/llama-memory-hybrid.h
src/llama-model.cpp
src/llama-vocab.cpp
tools/imatrix/README.md
tools/imatrix/imatrix.cpp

Updates dev branch with latest release (b6081) from ggml-org/llama.cpp

Sync master with upstream release b6081

---

.github/workflows/build.yml
ggml/src/ggml-webgpu/ggml-webgpu.cpp

Updates dev branch with latest release (b6097) from ggml-org/llama.cpp

Sync master with upstream release b6097

---

convert_hf_to_gguf.py
ggml/CMakeLists.txt
ggml/cmake/ggml-config.cmake.in
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/fattn-mma-f16.cuh
ggml/src/ggml-cuda/fattn.cu
ggml/src/ggml-cuda/ggml-cuda.cu
ggml/src/ggml-cuda/mma.cuh
ggml/src/ggml-cuda/mmf.cu
ggml/src/ggml-cuda/mmf.cuh
ggml/src/ggml-cuda/mmq.cu
ggml/src/ggml-cuda/mmq.cuh
ggml/src/ggml-cuda/mmvf.cu
ggml/src/ggml-cuda/mmvf.cuh
ggml/src/ggml-cuda/vendors/hip.h
ggml/src/ggml-cuda/vendors/musa.h
ggml/src/ggml-hip/CMakeLists.txt
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_base.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm1.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm2.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_split_k_reduce.comp
gguf-py/gguf/tensor_mapping.py
requirements/requirements-convert_hf_to_gguf.txt
scripts/compare-llama-bench.py
src/llama-quant.cpp
tools/mtmd/requirements.txt

Updates dev branch with latest release (b6115) from ggml-org/llama.cpp

Sync master with upstream release b6115

---

ggml/src/ggml-cuda/fattn-tile-f16.cu
ggml/src/ggml-cuda/fattn-tile-f32.cu
ggml/src/ggml-cuda/fattn-wmma-f16.cu
ggml/src/ggml-cuda/fattn.cu
ggml/src/ggml-cuda/ssm-scan.cu

Updates dev branch with latest release (b6123) from ggml-org/llama.cpp

Sync master with upstream release b6123

---

ggml/src/ggml-cann/aclnn_ops.cpp
ggml/src/ggml-cann/ggml-cann.cpp
ggml/src/ggml-cuda/CMakeLists.txt
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/fattn-wmma-f16.cu
ggml/src/ggml-cuda/vendors/hip.h
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-opencl/kernels/add.cl
ggml/src/ggml-sycl/ggml-sycl.cpp

Updates dev branch with latest release (b6140) from ggml-org/llama.cpp

Sync master with upstream release b6140

---

convert_hf_to_gguf.py
ggml/src/ggml-opencl/CMakeLists.txt
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-opencl/kernels/flash_attn_f16.cl
ggml/src/ggml-opencl/kernels/flash_attn_f32.cl
ggml/src/ggml-opencl/kernels/flash_attn_f32_f16.cl
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm1.comp
ggml/src/ggml-vulkan/vulkan-shaders/generic_binary_head.comp
ggml/src/ggml-vulkan/vulkan-shaders/mul_mm.comp
ggml/src/ggml-vulkan/vulkan-shaders/multi_add.comp
ggml/src/ggml-vulkan/vulkan-shaders/utils.comp
ggml/src/ggml-vulkan/vulkan-shaders/vulkan-shaders-gen.cpp
gguf-py/gguf/constants.py
gguf-py/gguf/tensor_mapping.py
tests/test-backend-ops.cpp
tools/mtmd/clip-impl.h
tools/mtmd/clip.cpp

Updates dev branch with latest release (b6183) from ggml-org/llama.cpp

Sync master with upstream release b6183

---

common/arg.cpp
common/chat.cpp
common/common.h
ggml/src/ggml-cann/aclnn_ops.cpp
ggml/src/ggml-cann/common.h
ggml/src/ggml-cpu/arch-fallback.h
ggml/src/ggml-cpu/arch/powerpc/quants.c
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-opencl/ggml-opencl.cpp
src/llama-context.cpp
src/llama-model.cpp
src/llama-model.h
tests/test-chat.cpp
tools/batched-bench/batched-bench.cpp
tools/server/tests/unit/test_basic.py
tools/server/tests/unit/test_completion.py
tools/server/tests/unit/test_ctx_shift.py
tools/server/tests/unit/test_embedding.py
tools/server/tests/unit/test_infill.py
tools/server/tests/unit/test_lora.py
tools/server/tests/unit/test_rerank.py
tools/server/tests/unit/test_security.py
tools/server/tests/unit/test_slot_save.py
tools/server/tests/unit/test_speculative.py
tools/server/tests/unit/test_tokenize.py
tools/server/tests/unit/test_tool_call.py
tools/server/tests/utils.py
tools/tts/tts.cpp

Updates dev branch with latest release (b6209) from ggml-org/llama.cpp

Sync master with upstream release b6209

---

docs/function-calling.md
ggml/src/ggml-cann/ggml-cann.cpp
ggml/src/ggml-vulkan/ggml-vulkan.cpp
scripts/compare-llama-bench.py
tools/server/README.md

Updates dev branch with latest release (b6323) from ggml-org/llama.cpp

Sync master with upstream release b6323

---

common/arg.cpp
common/common.cpp
common/common.h
docs/build.md
examples/diffusion/diffusion-cli.cpp
ggml/CMakeLists.txt
ggml/src/ggml-backend.cpp
ggml/src/ggml-cpu/CMakeLists.txt
ggml/src/ggml-cpu/kleidiai/kernels.cpp
ggml/src/ggml-cpu/kleidiai/kernels.h
ggml/src/ggml-cpu/kleidiai/kleidiai.cpp
ggml/src/ggml-cuda/conv2d.cu
include/llama.h
scripts/server-bench.py
scripts/tool_bench.py
src/llama-context.cpp
src/llama-graph.cpp
src/llama-graph.h
src/llama-impl.h
src/llama-model.cpp
src/llama.cpp
tools/batched-bench/batched-bench.cpp
tools/llama-bench/llama-bench.cpp
tools/server/tests/unit/test_ctx_shift.py
tools/server/tests/unit/test_speculative.py
tools/server/tests/utils.py

Updates dev branch with latest release (b6327) from ggml-org/llama.cpp

Sync master with upstream release b6327

---

ci/run.sh
common/arg.cpp
common/common.h
ggml/include/ggml-backend.h
ggml/src/ggml-backend.cpp
ggml/src/ggml-metal/ggml-metal.m
ggml/src/ggml-metal/ggml-metal.metal
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm1.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_cm2.comp
ggml/src/ggml-vulkan/vulkan-shaders/flash_attn_split_k_reduce.comp
ggml/src/ggml-vulkan/vulkan-shaders/get_rows.comp
ggml/src/ggml-vulkan/vulkan-shaders/get_rows_quant.comp
ggml/src/ggml-vulkan/vulkan-shaders/mul_mm.comp
ggml/src/ggml-vulkan/vulkan-shaders/mul_mm_cm2.comp
ggml/src/ggml-vulkan/vulkan-shaders/vulkan-shaders-gen.cpp
src/llama-context.cpp
src/llama-context.h
tools/server/README.md
tools/server/server.cpp
tools/server/tests/utils.py

Updates dev branch with latest release (b6337) from ggml-org/llama.cpp

Sync master with upstream release b6337

---

ggml/src/ggml-cpu/arch/s390/quants.c
ggml/src/ggml-cpu/ggml-cpu-impl.h
ggml/src/ggml-vulkan/ggml-vulkan.cpp
ggml/src/ggml-vulkan/vulkan-shaders/im2col_3d.comp
ggml/src/ggml-vulkan/vulkan-shaders/mul_mm.comp
ggml/src/ggml-vulkan/vulkan-shaders/pad.comp
ggml/src/ggml-vulkan/vulkan-shaders/types.comp
ggml/src/ggml-vulkan/vulkan-shaders/vulkan-shaders-gen.cpp
ggml/src/ggml-webgpu/ggml-webgpu.cpp
tests/test-backend-ops.cpp

Updates dev branch with latest release (b6407) from ggml-org/llama.cpp

Sync master with upstream release b6407

---

.devops/rocm.Dockerfile
.github/workflows/release.yml
ggml/src/ggml-cuda/im2col.cu
ggml/src/ggml-cuda/mmf.cuh
ggml/src/ggml-sycl/binbcast.cpp
ggml/src/ggml-sycl/binbcast.hpp
ggml/src/ggml-sycl/ggml-sycl.cpp
tools/perplexity/perplexity.cpp
tools/run/run.cpp

Updates dev branch with latest release (b6482) from ggml-org/llama.cpp

Sync master with upstream release b6482

---

.github/workflows/build-riscv-native.yml
.github/workflows/build.yml
ci/README-MUSA.md
ci/README.md
ci/run.sh
ggml/src/ggml-opencl/CMakeLists.txt
ggml/src/ggml-opencl/ggml-opencl.cpp
ggml/src/ggml-opencl/kernels/cvt.cl
ggml/src/ggml-opencl/kernels/mul_mv_id_q8_0_f32.cl
ggml/src/ggml-opencl/kernels/mul_mv_id_q8_0_f32_flat.cl
ggml/src/ggml-opencl/kernels/mul_mv_q8_0_f32.cl
ggml/src/ggml-opencl/kernels/mul_mv_q8_0_f32_flat.cl
ggml/src/ggml-vulkan/ggml-vulkan.cpp

Updates dev branch with latest release (b6533) from ggml-org/llama.cpp

Sync master with upstream release b6533
